 
mutation mutationSharingMedicalInstitutionCancel($medicalInstitutionUserId: Int!){
  sharingMedicalInstitutionCancel(medicalInstitutionUserId: $medicalInstitutionUserId){
    id
    setting{
      id
      name
    }
  }
}
