 
mutation mutationSharingMedicalInstitutionAccept($medicalInstitutionUserId: Int!){
  sharingMedicalInstitutionAccept(medicalInstitutionUserId: $medicalInstitutionUserId){
    id
    setting{
      id
      name
    }
  }
}
