 
query queryHome{
  currentUser{
    id
    setting{
      id
      sharelingCode
      gender
      postalCode
      birthYear
      showBodyWeight
      showSaltConcentration
      showStepDownMedicineState
    }
  }
  unreadInformationCount
  now
}
