 
query queryProfile{
  currentUser{
    id
    healthStatus{
      id
      smokingStatus
      diabetesStatus
      cerebrovascularDiseasStatus
      heartLesionStatus
      kidneySiseaseStatus
      vascularLesionStatus
      diseaseDeathRelativesStatus
    }
  }
}
